workflow:
  rules:
    # can not be executed as part of merge request
    # this avoids weird pipeline behavior (rules:changes comparing to dev branch), 
    # however might produce more job runs
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - when: always # Run pipeline in all other cases

trigger_child_de_modules:
 trigger:
   include:
     - local: src/data-module/.gitlab-ci.yml
   strategy: depend
 rules:
   - changes:
     - src/data-modules/**/*
